export const providerData = [
  {
    id: 1,
    name: "City Care Hospital",
    category: "Healthcare Services",
    subCategory: "Hospitals",
    specialization: "Cardiology",
    rating: 4.6,
    totalReviews: 420,
    experience: "15+ years",
    consultationFee: 1200,
    nextAvailableSlot: "Today • 6:00 PM",
    responseTime: "10 mins",
    isVerified: true,
    description:
      "Multi-specialty hospital providing advanced cardiac care with experienced doctors and modern infrastructure.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/hospital.webp",
  },

  {
    id: 2,
    name: "Glow Beauty Salon",
    category: "Personal Care & Wellness",
    subCategory: "Salons",
    rating: 4.4,
    totalReviews: 210,
    experience: "8+ years",
    consultationFee: 600,
    nextAvailableSlot: "Tomorrow • 11:00 AM",
    responseTime: "20 mins",
    isVerified: true,
    description:
      "Premium beauty salon offering hair, skin, makeup, and bridal services with certified professionals.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/salon.jpg",
  },

  {
    id: 3,
    name: "Smile Dental Clinic",
    category: "Healthcare Services",
    subCategory: "Dental Clinics",
    specialization: "Dentistry",
    rating: 4.5,
    totalReviews: 180,
    experience: "12+ years",
    consultationFee: 700,
    nextAvailableSlot: "Today • 5:15 PM",
    responseTime: "15 mins",
    isVerified: true,
    description:
      "Advanced dental clinic specializing in painless treatments, cosmetic dentistry, and implants.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/dental.jpg",
  },

  {
    id: 4,
    name: "Flex Physio Center",
    category: "Healthcare Services",
    subCategory: "Physiotherapy Centers",
    specialization: "Orthopedics",
    rating: 4.3,
    totalReviews: 160,
    experience: "10+ years",
    consultationFee: 900,
    nextAvailableSlot: "Tomorrow • 9:30 AM",
    responseTime: "25 mins",
    isVerified: true,
    description:
      "Physiotherapy center offering personalized rehab programs for joint, spine, and sports injuries.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/physio.jpg",
  },

  {
    id: 5,
    name: "HealthPlus Diagnostic Lab",
    category: "Healthcare Services",
    subCategory: "Diagnostic / Pathology Laboratories",
    rating: 4.2,
    totalReviews: 300,
    experience: "18+ years",
    consultationFee: 500,
    nextAvailableSlot: "Today • 2:00 PM",
    responseTime: "30 mins",
    isVerified: true,
    description:
      "Trusted diagnostic laboratory providing accurate pathology tests and home sample collection.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Pathology laboratories.jpg",
  },

  {
    id: 6,
    name: "Vision Eye Care",
    category: "Healthcare Services",
    subCategory: "Eye Care Centers",
    specialization: "Ophthalmology",
    rating: 4.7,
    totalReviews: 260,
    experience: "14+ years",
    consultationFee: 1000,
    nextAvailableSlot: "Tomorrow • 4:00 PM",
    responseTime: "12 mins",
    isVerified: true,
    description:
      "Comprehensive eye care center offering vision testing, cataract surgery, and LASIK services.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Eye Care Centers.jpg",
  },

  {
    id: 7,
    name: "Zen Yoga Studio",
    category: "Personal Care & Wellness",
    subCategory: "Yoga & Fitness Studios",
    rating: 4.8,
    totalReviews: 350,
    experience: "10+ years",
    consultationFee: 500,
    nextAvailableSlot: "Tomorrow • 7:00 AM",
    responseTime: "5 mins",
    isVerified: true,
    description:
      "Peaceful yoga studio offering certified instructors, meditation sessions, and wellness programs.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Yoga & Fitness Studios.jpg",
  },

  {
    id: 8,
    name: "Relax Spa & Wellness",
    category: "Personal Care & Wellness",
    subCategory: "Spas",
    rating: 4.6,
    totalReviews: 190,
    experience: "9+ years",
    consultationFee: 1500,
    nextAvailableSlot: "Today • 7:30 PM",
    responseTime: "18 mins",
    isVerified: true,
    description:
      "Luxury spa providing massage therapies, body treatments, and stress-relief wellness programs.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/personal Care & Wellness.jpg",
  },

  {
    id: 9,
    name: "Prime Legal Associates",
    category: "Professional & Consulting Services",
    subCategory: "Legal Consultants / Lawyers",
    rating: 4.4,
    totalReviews: 140,
    experience: "20+ years",
    consultationFee: 2000,
    nextAvailableSlot: "Tomorrow • 12:00 PM",
    responseTime: "30 mins",
    isVerified: true,
    description:
      "Experienced legal firm providing services in corporate law, civil cases, and legal advisory.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Legal Consultants Lawyers.jpg",
  },

  {
    id: 10,
    name: "Bright Future Coaching",
    category: "Education & Training",
    subCategory: "Coaching Centers",
    rating: 4.5,
    totalReviews: 500,
    experience: "11+ years",
    consultationFee: 400,
    nextAvailableSlot: "Tomorrow • 3:00 PM",
    responseTime: "10 mins",
    isVerified: true,
    description:
      "Renowned coaching institute for competitive exams with experienced faculty and proven results.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Education & Training.jpg",
  },

  {
    id: 11,
    name: "Growth Financial Advisors",
    category: "Professional & Consulting Services",
    subCategory: "Financial Advisors",
    rating: 4.3,
    totalReviews: 120,
    experience: "13+ years",
    consultationFee: 1800,
    nextAvailableSlot: "Tomorrow • 5:00 PM",
    responseTime: "20 mins",
    isVerified: true,
    description:
      "Certified financial advisors helping individuals and businesses with investment and tax planning.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Financial Advisors.jpg",
  },

  {
    id: 12,
    name: "SkillPro Training Institute",
    category: "Education & Training",
    subCategory: "Training Institutes",
    rating: 4.6,
    totalReviews: 260,
    experience: "9+ years",
    consultationFee: 700,
    nextAvailableSlot: "Today • 6:45 PM",
    responseTime: "15 mins",
    isVerified: true,
    description:
      "Professional training institute offering skill development and industry-oriented certification programs.",
    city: "Silvassa",
    image: "/src/assets/images/ProviderImages/Training Institutes.jpg",
  },
];
